// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";

function s(prim) {
  return prim;
}

function App(Props) {
  return React.createElement("h2", undefined, "Hello");
}

var make = App;

export {
  s ,
  make ,
  
}
/* react Not a pure module */
